# Generated by Django 3.1.6 on 2021-03-04 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gensimutility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('path', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=4000, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=' description placeholder ', max_length=200000),
            preserve_default=False,
        ),
    ]
