# Generated by Django 3.1.6 on 2021-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensimutility', '0003_blog_written_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=400000, unique=True)),
                ('email_addr', models.EmailField(max_length=30, unique=True)),
                ('profile_pic', models.CharField(max_length=30)),
            ],
        ),
    ]
