# Generated by Django 3.1.6 on 2021-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensimutility', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='applications',
            field=models.TextField(default='Advantages placeholder', max_length=200000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='disadvantages',
            field=models.TextField(default='disadvantages placeholder', max_length=200000),
            preserve_default=False,
        ),
    ]
