# Generated by Django 3.1.6 on 2021-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensimutility', '0005_auto_20210311_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='advantages',
            field=models.TextField(default='Advantages placeholder', max_length=200000),
            preserve_default=False,
        ),
    ]
