# Generated by Django 3.1.6 on 2021-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gensimutility', '0006_blog_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='formula_pic',
            field=models.CharField(default='plac', max_length=50),
            preserve_default=False,
        ),
    ]
